### PR TITLE
eXternal Optimizations

### PR DESCRIPTION
**Pull request by padrino121**
Testing on 8X GPU system, 75H/s per Radeon 470 https://bitcointalk.org/index.php?topic=1666489.msg16843510#msg16843510

### CODE REVIEW

**Comment by N5QM** [comment]
Tested on single RX 470/4GB system with GPU at 1074 and VRAM at 1945 and received the following results.

Total 68.1 sol/s [dev0 70.0] 19 shares
Total 69.0 sol/s [dev0 70.9] 19 shares
Total 69.9 sol/s [dev0 70.8] 19 shares
Total 69.7 sol/s [dev0 70.7] 19 shares
Total 69.7 sol/s [dev0 71.7] 19 shares
Total 70.3 sol/s [dev0 72.2] 19 shares
Total 70.2 sol/s [dev0 71.8] 19 shares
Total 70.2 sol/s [dev0 70.5] 19 shares
Total 69.6 sol/s [dev0 69.4] 19 shares
Total 68.9 sol/s [dev0 67.0] 19 shares
Total 69.7 sol/s [dev0 68.7] 19 shares
Total 69.9 sol/s [dev0 67.7] 19 shares
Total 69.4 sol/s [dev0 67.8] 19 shares
Total 69.2 sol/s [dev0 67.2] 20 shares
Total 68.5 sol/s [dev0 67.1] 20 shares
Total 68.6 sol/s [dev0 67.1] 20 shares

**Comment by maharius** [comment]
~60 sol/s each on HD7970 and R9 280

**Comment by Kubuxu** [comment]
Getting about 70Sols/s on RX480

**Comment by asluchevskiy** [comment]
~70 RX470 1500>1750 timings, stock clocks

**Comment by Kubuxu** [comment]
Getting about 64-68 on GTX1070 on one instance.

**Comment by mbevand** [comment]
Merged and released into SILENTARMY v5 - thanks eXtremal!
https://github.com/mbevand/silentarmy/commit/b879b795141b95d0878e93bd9ae5cab120149891

**Pull request closed without merging**
